### ISSUE TITLE
Fix gh-pages demo

### ISSUE THREAD

**Issue by cjcolvar** [avalonmediasystem/react-iiif-media-player#22]
The manifest used on the demo page references pawpaw.dlib.indiana.edu which has been decommissioned.  This could be changed to reference demo.avalonmediasystem.org or to a sample manifest from a IIIF github organization source.

**Comment by Dananji** [comment]
@cjcolvar When you mentioned `a sample manifest from IIIF github organization source`, did you mean these https://github.com/IIIF/cookbook-recipes/tree/master/recipe ?

**Comment by cjcolvar** [comment]
I think we have a manifest that we've contributed that would be good for using but I'm not sure where it lives (or the best one to reference).  I don't think the cookbook recipes has the one I'm thinking of.  I'll check with @mcwhitaker and we'll post a good url here as a comment.

**Comment by Dananji** [comment]
Thanks!

**Comment by mcwhitaker** [comment]
@cjcolvar  I have updated the manifest with this url: http://dlib.indiana.edu/iiif_av/mahler-symphony-3/mahler-symphony-3.json

As for the language attribute, I put "en" everywhere although I know some of them are German. It was just easier to use a find/replace to edit all labels.
Also, the canvases do not have width and height because this is an audio file. I think this is good, but do you see any reason why we should add some space dimensions besides the time dimension of duration? 
If you could review the manifest for compliance, that would be appreciated.
