### ISSUE TITLE
[IIIF Player] Supports multiple sections

### ISSUE THREAD

**Issue by Dananji** [avalonmediasystem/react-iiif-media-player#27]
### Description

Avalon player supports playing multiple sections one after the other. IIIF player doesn't identify these different sections from the manifest, instead treats the second section as part of the structure of the first section. The two screenshots below are for the same media object,

Sections in Avalon;
![Screenshot from 2020-03-02 11-39-14.png](https://images.zenhubusercontent.com/5cc1c66b3244e00362de97ea/29f0f1d9-ee58-48ce-b96f-4fb756f25d4d)

In iiif-player;
![Screenshot from 2020-03-02 11-39-27.png](https://images.zenhubusercontent.com/5cc1c66b3244e00362de97ea/902dfc05-9594-43fd-acfd-bc29f69acdc5)

**Comment by cjcolvar** [comment]
This issue is complicated.  I think the iiif-player is handling things correctly here since all of the content is in a single IIIF range.  If this hierarchy is not ideal then we should look at how we model our items in the IIIF manifest.  Maybe it would be good to talk through how we modeled the content in the manifest (ranges and canvases) since it might have impacts on how we instantiate ME.js instances.
