### ISSUE TITLE
[IIIF Player] Add Create Thumbnail

### ISSUE THREAD

**Issue by Dananji** [avalonmediasystem/react-iiif-media-player#32]
### Description

Add `Create Thumbnail` support for video in iiif player like in avalon player;
![Screenshot from 2020-03-02 14-51-03.png](https://images.zenhubusercontent.com/5cc1c66b3244e00362de97ea/90642de7-9012-43b1-a385-31f85d6cfb18)

### Done Looks Like

iiif player allows users to create thumbnail for video

**Comment by cjcolvar** [comment]
Do we need to make a distinction between read-only features and features that involve writing to the server (create thumbnail, add to playlist)?  Maybe these should be apart from the player like create timeline is?  That might simplify the IIIF implementation since we wouldn't need to find an equivalent in IIIF.

**Comment by Dananji** [comment]
Yes that makes sense. So the extra functionalities that's coming in from Avalon won't live in the player. Does that include the markers in playlists?

**Comment by cjcolvar** [comment]
I feel like playlists is an entirely different thing at this point since we haven't done the work to model the playlist in a IIIF manifest.  I think it'd make sense to get the player on the view page then do playlists as a second step.
